### ISSUE TITLE
Evaluate broken

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#57] opened 2020-02-04 15:14 UTC
@kittaakos , the Dialog grammar seems to be broken in a way that puzzles me. Create a new project and create a new .dialog file with this content:
` uri "http://sadl.org/evaluate.dialog" alias ev.
 
 External CAL_SOS(double T, double G, double R, double Q) 
 				  returns double: "http://com.ge.research.darpa.aske.kchain.CAL_SOS".
 				  
 Evaluate CAL_SOS(245.6, 1.4, 8.314, 3056).`

There will be grammar errors on the last statement. This used to work, and looking at the grammar I don't see a cause. The error message doesn't make sense to me.

**Comment by kittaakos** [comment] 2020-02-04 15:19
@crapo, which branch are you working on?

**Comment by crapo** [comment] 2020-02-04 15:20
Or, if it's easier, the dialog.tests DialogTest dummy_test has this issue on the evaluate line with multiple arguments.

sadlos: MissingPatterns, ASKE TA1: master.

**Comment by kittaakos** [comment] 2020-02-04 15:37
I have compiler errors in `com.ge.research.sadl.jena.IntermediateFormTranslator`. Do you know how to fix them?

**Comment by crapo** [comment] 2020-02-04 15:53
I don't have any errors. What and where are you seeing errors?

**Comment by crapo** [comment] 2020-02-04 15:56
you have to rebuild the reasoner-api and reasoner-impl jars
and update the jena 3rd party project

**Comment by kittaakos** [comment] 2020-02-04 16:36
I could reproduce it with a simple parser test. When was the last time it worked? I have to check the SADL grammar changes too.

```java
package com.ge.research.sadl.darpa.aske.tests

import com.ge.research.sadl.sADL.SadlModel
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DialogInjectorProvider)
class DialogParsingTest {

	@Inject
	extension ParseHelper<SadlModel> parseHelper

	@Test
	def void evalStatement_0_params() {
		'''
			uri "http://test".
			Evaluate CAL_SOS().
		'''.assertNoErrors
	}

	@Test
	def void evalStatement_1_params() {
		'''
			uri "http://test".
			Evaluate CAL_SOS(1).
		'''.assertNoErrors
	}

	@Test
	def void evalStatement_2_params() {
		'''
			uri "http://test".
			Evaluate CAL_SOS(1, 2).
		'''.assertNoErrors
	}

	private def assertNoErrors(CharSequence s) {
		val model = s.parse
		Assert.assertNotNull(model)
		val errors = model.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}

}
```

**Comment by crapo** [comment] 2020-02-04 16:41
I'm not sure exactly when it last worked. But we used this statement in demos to DARPA in October I believe.

**Comment by kittaakos** [comment] 2020-02-04 16:55
> DARPA in October

I see. I am looking into this, but it is a bit hard to trace back now, I am not sure if I can help a lot this week 😕  By the way, I created a small lexer test, and it is correct.

```java
package com.ge.research.sadl.darpa.aske.tests

import com.ge.research.sadl.darpa.aske.parser.antlr.lexer.InternalDialogLexer
import com.google.inject.Inject
import com.google.inject.Provider
import org.antlr.runtime.ANTLRStringStream
import org.antlr.runtime.Token
import org.eclipse.xtext.parser.antlr.Lexer
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

import static java.lang.System.lineSeparator
import static com.ge.research.sadl.darpa.aske.parser.antlr.internal.InternalDialogParser.*
import static org.junit.Assert.assertEquals

@RunWith(XtextRunner)
@InjectWith(DialogInjectorProvider)
class DialogLexerTest {

	@Inject
	Provider<InternalDialogLexer> lexer

	@Test
	def void eval_0_params() {
		val it = '''
			uri "http://test".
			Evaluate CAL_SOS().
		'''.createLexer
		assertNextToken(Uri, 'uri')
		assertNextToken(RULE_WS, ' ')
		assertNextToken(RULE_STRING, '"http://test"')
		assertNextToken(FullStop, '.')
		assertNextToken(RULE_WS, lineSeparator)
		assertNextToken(Evaluate, 'Evaluate')
		assertNextToken(RULE_WS, ' ')
		assertNextToken(RULE_ID, 'CAL_SOS')
		assertNextToken(LeftParenthesis, '(')
		assertNextToken(RightParenthesis, ')')
		assertNextToken(FullStop, '.')
		assertNextToken(RULE_WS, lineSeparator)
		nextToken.assertEndOfTokens
	}

	@Test
	def void eval_2_params() {
		val it = '''
			uri "http://test".
			Evaluate CAL_SOS(1, 2).
		'''.createLexer
		assertNextToken(Uri, 'uri')
		assertNextToken(RULE_WS, ' ')
		assertNextToken(RULE_STRING, '"http://test"')
		assertNextToken(FullStop, '.')
		assertNextToken(RULE_WS, lineSeparator)
		assertNextToken(Evaluate, 'Evaluate')
		assertNextToken(RULE_WS, ' ')
		assertNextToken(RULE_ID, 'CAL_SOS')
		assertNextToken(LeftParenthesis, '(')
		assertNextToken(RULE_NUMBER, '1')
		assertNextToken(Comma, ',')
		assertNextToken(RULE_WS, ' ')
		assertNextToken(RULE_NUMBER, '2')
		assertNextToken(RightParenthesis, ')')
		assertNextToken(FullStop, '.')
		assertNextToken(RULE_WS, lineSeparator)
		nextToken.assertEndOfTokens
	}

	private def createLexer(CharSequence cs) {
		return lexer.get => [
			charStream = new ANTLRStringStream(cs.toString)
		]
	}

	private def assertEndOfTokens(Token token) {
		token.assertEquals(-1, null)
	}

	private def void assertNextToken(Lexer it, int id, String text) {
		nextToken.assertEquals(id, text)
	}

	private def void assertEquals(Token token, int id, String text) {
		assertEquals('''Expected token text was: «text», actual was: «token.text»''', id, token.type)
		if (text !== null) {
			assertEquals('''Expected token was: «id»''', text, token.text)
		}
	}
}
```

**Comment by crapo** [comment] 2020-02-04 16:58
What does that mean? The lexer test passes but the grammar still is deemed invalid? The grammar for this seems pretty straightforward and the test cases seem to conform, which is what puzzles me....

**Comment by kittaakos** [comment] 2020-02-04 17:32
> what puzzles me

Mee too. Especially, the model seems to be correct after the parsing:

![Screen Shot 2020-02-04 at 18 32 00](https://user-images.githubusercontent.com/1405703/73770411-abad4e80-477c-11ea-9067-aceb0e585217.jpg)


I'll try to figure out something...

**Comment by kittaakos** [comment] 2020-02-05 08:33
@crapo, I could not build SADL. So the compiler errors are still an issue on my side.

I am on this commit in SADL: https://github.com/crapo/sadlos2/commit/85f77b1e and did the following:
```
git clean -ffxqd && git status -s && git rev-parse --short HEAD && mvn clean && mvn verify
```
Is there anything else I have to run before executing the Maven build?

```
[INFO] Reactor Summary:
[INFO] 
[INFO] com.ge.research.sadl.parent ........................ SUCCESS [  0.370 s]
[INFO] com.ge.research.sadl.xtextgenerator ................ SUCCESS [  9.498 s]
[INFO] Reasoner/Translator ................................ SUCCESS [  0.000 s]
[INFO] Reasoner/Translator API ............................ SUCCESS [  2.451 s]
[INFO] Reasoner/Translator Implementation ................. SUCCESS [  0.750 s]
[INFO] com.ge.research.jena ............................... SUCCESS [  0.736 s]
[INFO] com.ge.research.sadl.errorgenerator ................ SUCCESS [  0.121 s]
[INFO] com.ge.research.sadl ............................... SUCCESS [ 37.877 s]
[INFO] com.ge.research.sadl.jena .......................... SUCCESS [  1.267 s]
[INFO] Jena Reasoner/Translator Plugin for SADL ........... SUCCESS [  0.379 s]
[INFO] com.ge.research.sadl.ide ........................... SUCCESS [  4.347 s]
[INFO] com.ge.research.sadl.ui ............................ FAILURE [  4.505 s]
[INFO] com.ge.research.sadl.externalmodels ................ SKIPPED
[INFO] com.ge.research.sadl.target ........................ SKIPPED
[INFO] com.ge.research.sadl.tests ......................... SKIPPED
[INFO] com.ge.research.sadl.ui.tests ...................... SKIPPED
[INFO] SWI-Prolog Reasoner/Translator Plugin for SADL ..... SKIPPED
[INFO] com.ge.research.sadl.importer ...................... SKIPPED
[INFO] com.ge.research.sadl.importer.ide .................. SKIPPED
[INFO] com.ge.research.sadl.importer.tests ................ SKIPPED
[INFO] com.ge.research.sadl.importer.ui ................... SKIPPED
[INFO] com.ge.research.sadl.importer.ui.tests ............. SKIPPED
[INFO] SADL Test Suite .................................... SKIPPED
[INFO] com.ge.research.sadl.testsuite.ide ................. SKIPPED
[INFO] com.ge.research.sadl.testsuite.tests ............... SKIPPED
[INFO] com.ge.research.sadl.testsuite.ui .................. SKIPPED
[INFO] com.ge.research.sadl.testsuite.ui.tests ............ SKIPPED
[INFO] com.ge.research.sadl.applications .................. SKIPPED
[INFO] com.ge.research.sadl.perspective ................... SKIPPED
[INFO] SADL 3 ............................................. SKIPPED
[INFO] SADL 3 Update Site ................................. SKIPPED
[INFO] SADL Knowledge Services ............................ SKIPPED
[INFO] SadlServer API ..................................... SKIPPED
[INFO] SadlServer Implementation .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:13 min
[INFO] Finished at: 2020-02-05T09:27:09+01:00
[INFO] Final Memory: 204M/1600M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.3.0:compile (default-compile) on project com.ge.research.sadl.ui: Compilation failure: Compilation failure: 
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[696] 
[ERROR] 	csvImporter = new CsvImporter(cmgr);
[ERROR] 	              ^^^^^^^^^^^^^^^^^^^^^
[ERROR] The constructor CsvImporter(IConfigurationManager) is undefined
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[707] 
[ERROR] 	csvImporter.setImports(imports);
[ERROR] 	            ^^^^^^^^^^
[ERROR] The method setImports(List<String>) from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[708] 
[ERROR] 	csvImporter.setTemplates(template); //(templateString);
[ERROR] 	            ^^^^^^^^^^^^
[ERROR] The method setTemplates(String) from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[711] 
[ERROR] 	jenaTDBFolder = csvImporter.getSaveAsFileName();
[ERROR] 	                            ^^^^^^^^^^^^^^^^^
[ERROR] The method getSaveAsFileName() from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[728] 
[ERROR] 	ots = new OwlToSadl(csvImporter.getOwlModel(), csvImporter.getModelName());
[ERROR] 	                                ^^^^^^^^^^^
[ERROR] The method getOwlModel() from the type CsvImporter refers to the missing type OntModel
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[738] 
[ERROR] 	contentStream = csvImporter.getOwlModel(null).getInputStream();
[ERROR] 	                            ^^^^^^^^^^^
[ERROR] The method getOwlModel(String) from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[757] 
[ERROR] 	String fn = csvImporter.getSaveAsFileName();
[ERROR] 	                        ^^^^^^^^^^^^^^^^^
[ERROR] The method getSaveAsFileName() from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[781] 
[ERROR] 	csvImporter.saveSadlProjectOwlFileMapping(namespace, targetResource.getRawLocation().toPortableString(), null);
[ERROR] 	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method saveSadlProjectOwlFileMapping(String, String, String) from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[793] 
[ERROR] 	long numTriples = csvImporter.processImport();
[ERROR] 	                              ^^^^^^^^^^^^^
[ERROR] The method processImport() from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] /Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/imports/CsvImportOperation.java:[823] 
[ERROR] 	csvImporter.saveSadlProjectOwlFileMapping(namespace, owlOutputFile, null);
[ERROR] 	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method saveSadlProjectOwlFileMapping(String, String, String) from the type CsvImporter refers to the missing type ConfigurationException
[ERROR] 10 problems (10 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.ge.research.sadl.ui
```

**Comment by kittaakos** [comment] 2020-02-05 09:31
See: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/60

**Comment by crapo** [comment] 2020-02-05 15:40
The CsvImporter is in the com.ge.research.sadl.jana-wrapper-for-sadl project. However, I don't have any diffs in MANIFEST or pom files for either this or the sadl.ui projects. Puzzled.

**Comment by kittaakos** [comment] 2020-02-05 15:46
Can you build a fresh clone?

**Comment by crapo** [comment] 2020-02-05 15:48
do you mean fresh pull of code from github? not sure what you mean by clone...

**Comment by crapo** [comment] 2020-02-05 15:53
In this error: The constructor CsvImporter(IConfigurationManager) is undefined
what does the "(IConfigurationManager)" mean?

**Comment by crapo** [comment] 2020-02-05 16:03
sorry, I wasn't thinking in git terms. I've downloaded a clone and will try maven build

**Comment by kittaakos** [comment] 2020-02-05 16:04
> do you mean fresh pull of code from github?

Yes.

> not sure what you mean by clone...

```
git clone --single-branch -b MissingPatterns https://github.com/crapo/sadlos2.git \
&& cd sadlos2/sadl3/com.ge.research.sadl.parent \
&& mvn clean \
&& mvn verify
```

> The constructor CsvImporter(IConfigurationManager) is undefined
> what does the "(IConfigurationManager)" mean?

Did it fail on your side too? 😕

**Comment by crapo** [comment] 2020-02-05 16:05
still working....

**Comment by crapo** [comment] 2020-02-05 16:10
WRT the evaluate grammar, the use of Expression was to allow something like:
MyRect is a rectangle with length 10, with width 5.
Evaluate areaOfRectangle(length of MyRect, width of MyRect).
as well as
Evaluate areaOfRectangle(10 ft, 25 in).

**Comment by crapo** [comment] 2020-02-05 16:12
I do not have a maven failure in sadl.ui. I do have test failure in sadl.ui.tests, which I will look into.

**Comment by crapo** [comment] 2020-02-05 16:12
I'm using the MissingPatterns branch.

**Comment by kittaakos** [comment] 2020-02-05 16:12
> still working....

I have wiped my local maven cache and ran a fresh build again, now I have test failures only:
```
[INFO] com.ge.research.sadl.tests ......................... SUCCESS [ 23.796 s]
[INFO] com.ge.research.sadl.ui.tests ...................... FAILURE [ 26.763 s]
[INFO] SWI-Prolog Reasoner/Translator Plugin for SADL ..... SKIPPED
[INFO] com.ge.research.sadl.importer ...................... SKIPPED
[INFO] com.ge.research.sadl.importer.ide .................. SKIPPED
[INFO] com.ge.research.sadl.importer.tests ................ SKIPPED
[INFO] com.ge.research.sadl.importer.ui ................... SKIPPED
[INFO] com.ge.research.sadl.importer.ui.tests ............. SKIPPED
[INFO] SADL Test Suite .................................... SKIPPED
[INFO] com.ge.research.sadl.testsuite.ide ................. SKIPPED
[INFO] com.ge.research.sadl.testsuite.tests ............... SKIPPED
[INFO] com.ge.research.sadl.testsuite.ui .................. SKIPPED
[INFO] com.ge.research.sadl.testsuite.ui.tests ............ SKIPPED
[INFO] com.ge.research.sadl.applications .................. SKIPPED
[INFO] com.ge.research.sadl.perspective ................... SKIPPED
[INFO] SADL 3 ............................................. SKIPPED
[INFO] SADL 3 Update Site ................................. SKIPPED
[INFO] SADL Knowledge Services ............................ SKIPPED
[INFO] SadlServer API ..................................... SKIPPED
[INFO] SadlServer Implementation .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:50 min
[INFO] Finished at: 2020-02-05T17:10:58+01:00
[INFO] Final Memory: 196M/1531M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.3.0:test (default-test) on project com.ge.research.sadl.ui.tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/akos.kitta/Desktop/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.ge.research.sadl.ui.tests
akos.kitta@Akoss-MacBook-Pro com.ge.research.sadl.parent % 
```

So this issue seems to be resolved.

**Comment by crapo** [comment] 2020-02-05 16:20
ah, the test failures are because I thought I pushed test case fixes but I didn't.

**Comment by crapo** [comment] 2020-02-05 16:21
updated test cases pushed now

**Comment by crapo** [comment] 2020-02-05 17:49
OK, I did  a little thinking and a little reading, and I think the error is because the comma can either be between arguments or part of the expression. I don't think we need the expression to have commas, so I tried using ExpressionParameterized with comma disallowed, giving for the grammar:
EvalStatement returns SadlEquationInvocation:
	{SadlEquationInvocation} ('Evaluate'|'evaluate') name=SadlResource '(' (parameters+=ExpressionParameterized<true,false> ('{'units+=UNIT'}')? (',' parameters+=ExpressionParameterized<true,false> ('{'units+=UNIT'}')?)* )?')'
;

Now these are all parsed without error:
 Evaluate CAL_SOS(245.6, 1.4, 8.314, 3056).
 Evaluate CAL_SOS(245.6 {cm}, 1.4 {cm}, 8.314 {cm}, 3056 {cm}).

 MyRect is a Rectangle with ^length 5, with width 2.
 Evaluate CAL_SOS(2, width of MyRect, ^length of MyRect, 3.14).

**Comment by kittaakos** [comment] 2020-02-05 19:20
> Now these are all parsed without error:

Great! I closed the other PR (#61) where I used the booleans incorrectly.

I updated the actual PR (#60) with your grammar suggestion. On top of that, I have extracted the  `parameters` and `units` pairs into a  dedicated parser rule. (See the changes here: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/commit/fe776822355e6cd7342b8dd37fc072b0a40128e9#diff-17d5616c3f7cc3e0decb925ea31d3ed2) With the extraction, I would expect, it is easier to traverse the `SadlEquationInvocation` instances if you have something like this:
```java
Evaluate CAL_SOS(245.6 {m}, 1.4, 8.314, 3056 {cm}).
```

You do not have to deal with the `parameters` and `units` `EList` indexes, but you have a single list of `ParameterizedExpressionWithUnit` instances where the `expression`  is mandatory and the `unit` is optional.

Please rename the `ParameterizedExpressionWithUnit` if you do not like it. I have updated the PR, it is ready to be merged to the `master`: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/60

**Comment by crapo** [comment] 2020-02-05 19:32
Excellent, and thank you!! I'll merge as soon as I get a chance.

**Closed** 2020-02-06 13:26 UTC

**Comment by crapo** [comment] 2020-02-06 14:13
I did make one additional change. With the ParamterizedExpressionWithUnit construct, there is no need for a unit list. The expectation that any one argument to an Evaluate will only have one unit.
