### ISSUE TITLE
Content Assist Issues

### ISSUE THREAD

**Issue by GEGlobalResearch** [GEGlobalResearch/DARPA-ASKE-TA1#14] opened 2019-03-22 13:48 UTC
1. The content assist after keyword "uri" at the start of a model does not return a valild URI. Should work just like Sadl content assist. Not sure what's missing...
2. In a .dialog file in the Dialog editor, after the keyword "import" content assist puts up a list of imports but if one is selected it is inserted without quotes.

This uses master of DARPA-ASKE-TA1, AugmentedTypes branch of SADL.

**Comment by kittaakos** [comment] 2019-09-18 09:46
I am working on these items.

**Comment by kittaakos** [comment] 2019-09-18 11:14
> 1. The content assist after keyword "uri" at the start of a model does not return a valild URI. Should work just like Sadl content assist. Not sure what's missing...

It is done. Do you want a specific URL or is the SADL one fine?

![screencast 2019-09-18 13-13-19](https://user-images.githubusercontent.com/1405703/65143856-3bdd3800-da16-11e9-8c28-1eed9ef455e0.gif)

**Comment by kittaakos** [comment] 2019-09-18 11:17
> 2\. In a .dialog file in the Dialog editor, after the keyword "import" content assist puts up a list of imports but if one is selected it is inserted without quotes.

I could not reproduce it, perhaps it was fixed with the previous item.

![screencast 2019-09-18 13-15-36](https://user-images.githubusercontent.com/1405703/65143990-98405780-da16-11e9-8905-e73a9797ce87.gif)

**Comment by crapo** [comment] 2019-09-18 12:16
the uri content assist for dialog windows should provide a default URI for the model, derived from the dialog window filename, like it does for sadl. The import should only show work just like sadl. Content assist for target keyword would be like import.

**Closed** 2019-09-18 12:20 UTC
